version: '3.8'

services:
  mcp-hello:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-hello:latest
    container_name: mcp-hello-server
    restart: unless-stopped
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD", "python3", "-c", "import mcp_hello; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m
      - /var/tmp:rw,noexec,nosuid,size=50m

networks:
  default:
    driver: bridge
